# Generated by Django 5.2 on 2025-04-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produk',
        ),
    ]
